name: custom_scrollbar
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  draggable_scrollbar:
    git:
      url: https://github.com/thielepaul/flutter-draggable-scrollbar.git
      ref: cfd570035bf393de541d32e9b28808b5d7e602df
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
